# Generated by Django 3.2.8 on 2021-10-28 10:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('supplier', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='suppliers',
            name='supplier_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
